##Nathan Hinton
##This will be a wrapper for this menu that will allow autogeneration of captions using the vosk library

import os
from util.autogenCaptions import generateSrt, fix_caps

def run():
    filename = input('Path to video file: ')
    if not os.path.exists(filename):
        print("No video found at %s path"%filename)
        print("restarting the module")
        run()
    print("Converting video into audio... This may take a moment...")
    generatedSrt = generateSrt.convert(filename)
    i = input("Try to fix words and common mistakes? (Y, n): ")
    if i != 'n':
        generatedSrt = fix_caps.fix_caps(generatedSrt)
    i = input("Save captions in the same path? (Y, n): ")
    if i != 'n':
        p = os.path.split(filename)
        with open(p[0]+'/autogeneratedCaptions.srt', 'w') as file:
            file.write(generatedSrt)
    else:
        with open(i, 'w') as file:
            file.write(generatedSrt)

print("Loaded module autoGenCaptions")