##Nathan Hinton
##This is a wrapper module for the program to be given a filename and it will write the caption ro that path

import sys
from VTT import test_srt
from VTT import fix_caps
import tkinter.filedialog
import tkinter as tk


def convertFromVoice():
    window = tk.Tk()

    window.title("Change format from VTT to SRT")

    filename = tkinter.filedialog.askopenfilename()
    

    ##Keywords: path to convert, [outputFilename]
    print("Converting from video to srt...")
    output = test_srt.convert(filename)
    # print(output)
    # Recurse up the filepath as to generate a new filename
    for x in range(len(filename), 0, -1):
        if filename[0:x][-1] == '/':
            path = filename[0:x]
            break
    print("Reformatting SRT file to have caps in the right places...")
    fix_caps.fix_caps(output, path+"autogenerated.en_US.srt")
    print("Finished!")

